In [34]:
pwd

'C:\\Users\\U840T'

In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
x=np.array([
    [1,8,7],
    [1,4,10],
    [1,9,7],
    [1,7,10],
    [1,9,6],
    [1,4,8],
    [1,10,10],
    [1,2,7],
    [1,8,3],
    [1,7,5],
    [1,4,4],
    [1,4,6],
    [1,1,3],
    [1,2,5]
])
print(x)

[[ 1  8  7]
 [ 1  4 10]
 [ 1  9  7]
 [ 1  7 10]
 [ 1  9  6]
 [ 1  4  8]
 [ 1 10 10]
 [ 1  2  7]
 [ 1  8  3]
 [ 1  7  5]
 [ 1  4  4]
 [ 1  4  6]
 [ 1  1  3]
 [ 1  2  5]]


In [21]:
y=np.array([1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1])
print(y)

[ 1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1]


In [22]:
def li_reg(x,w):
    val=0
    for i,j in zip(x,w):
        val+=i*j
    return val

In [23]:
def give_sign(val):
    return np.sign(val)

In [24]:
def predict(x, w):
    hp=[]
    for i in x: 
        lr=li_reg(i,w)
        h=give_sign(lr)
        hp.append(h)
    return hp

In [25]:
def miss_class(py, y):
    miss=[]
    for i in range(len(y)):
        if py[i]!=y[i]:
            miss.append(i)
    return miss

In [26]:
def perceptron(x, y):
    w = np.random.rand(3)
   # print(w)
    
    py=predict(x,w)
    #print(py)
    
    miss=miss_class(py,y)
    #print(miss)
    
    while len(miss)>0:
        rnd=np.random.choice(miss)
        #print(rnd)
        
        rx=x[rnd]
        #print(rx)
        
        ry=y[rnd]
        #print(ry)
        
        w=w+rx*ry
        #print(w)
        
        py=predict(x,w)
        #print(py)
        
        miss=miss_class(py,y)
        
    return w

In [27]:
w=perceptron(x,y)
print(w)

[-40.37755337   1.79358434   4.24671053]


In [28]:
nx=np.array([1,5,5])
pp=predict([nx],w)
print(pp)

[-1.0]


In [29]:
pp=predict(x,w)
print(pp)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]


In [33]:
c=0;
y=y
for i in range(0,len(pp)):
    if(y[i]==pp[i]):
        c+=1
acc=(c/len(pp))*100
print(acc,'%')

100.0 %
